name: Node.js CI

on: push

jobs:
  codeceptjs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: actions/setup-node@v1
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          npm install
          npx codeceptjs run --steps
      env:
        CI: true
